package lk.ijse.util;

public enum TextField {
  COLLECT_ID, TS_ID,TS_NAME,TS_ADDRESS,TS_CONTACT,EMP_ID,ITEMID,ORDERID,PAYID,CODE,TEAID,NAME,ADDRESS,CONTACT,DATE,SALARY,DESCRIPTION,QUANTITY,PAYMETHOD,CATEGORY,PRICE,KGPRICE,DURATION
}
